[project]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "weather-project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean_data = "python scripts/split.py"

[dependencies]
python = ">=3.13.2,<3.14"
pandas = ">=2.2.3,<3"
pyarrow = ">=19.0.1,<20"
matplotlib = ">=3.10.1,<4"
fastparquet = ">=2024.11.0,<2025"
jupyterlab = ">=4.3.6,<5"
jupytext = ">=1.16.7,<2"
mystmd = ">=1.3.25,<2"
